#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/tetzable?serverTimezone=UTC  # 数据库连接 URL
#    username: root                      # 数据库用户名
#    password: 19911120Aa,                     # 数据库密码
#    driver-class-name: com.mysql.cj.jdbc.Driver   # MySQL 驱动类名
#    type: com.alibaba.druid.pool.DruidDataSource
# 数据源配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tetzable
    username: root
    password: 19911120Aa,
    driver-class-name: com.mysql.cj.jdbc.Driver

# JPA配置

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update